products = [
  {
    "_id": "1",
    "title": "Canon EOS 3000D DSLR Camera",
    "image": "/assets/camera.jpg",
    "description":
      "Designed for first-time DSLR owners on a budget – you can achieve impressive results straight out of the box with the EOS 3000D. With easy to use automatic shooting modes, 18MP sensor, Canon Camera Connect app integration and built-in feature guide, EOS 3000D is ready to shoot. The large 18MP APS-C sized sensor delivers impressive image quality, coupled with advanced Canon lens technology for images with beautiful background blur.",
    "brand": "Canon",
    "category": "eletronics",
    "price": 89.9,
    "countInStock": 100,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "2",
    "title": "Laser 20000mAh Charge Core Powerbank",
    "image": "/assets/powerbank.jpg",
    "description":
      "The Laser 2021 series of Powerbanks are small and light. You can charge two devices at the same time and we include a convenient charge cable which has a Micro-USB, USB-C and i-Device connector. Power Delivery (PD) ready means that the PD powerbank communicates with your device (via USB-C) to offer up a lot more power (up to 100w*) to get your device charged faster...perfect for the latest smartphones, tablets and even laptops This 20,000mAh (100Wh) Powerbank is airline (carry on) safe and can typically charge a smartphone up to 15 times*",
    "brand": "Laser",
    "category": "eletronics",
    "price": 41.95,
    "countInStock": 100,
    "rating": 3.5,
    "numReviews": 15,
  },
  {
    "_id": "3",
    "title": "OPPO A16s 4G 64GB",
    "image": "/assets/smartphone.jpg",
    "description":
      "The OPPO A16s lets you do more and stay online with its 5000mAh. Enjoy your favourite entertainment for hours, thanks to the HD+ screen and AI eye-care technology. Capture the perfect shot through the 13MP AI Triple Rear Camera. Now, you can turn your phone into a new way to pay with NFC!",
    "brand": "OPPO",
    "category": "eletronics",
    "price": 260.0,
    "countInStock": 100,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "4",
    "title": "V-Fitness Momentum Smart Watch",
    "image": "/assets/smartwatch.jpg",
    "description":
      "Say hello to your new companion for a healthier lifestyle. Make the most of your fitness regime with real-time activity tracking and monitor your health in greater detail using a slew of extra features including Heart Rate, Blood Pressure, Sleep Monitoring and more. There is beauty in its simplicity, the slim and lightweight design won’t slow you down during those important workouts, and the range of available colours guarantees you stay on trend.",
    "brand": "V-Fitness",
    "category": "eletronics",
    "price": 25.9,
    "countInStock": 100,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "5",
    "title": "Alcatel 1T 7",
    "image": "/assets/tablet.jpg",
    "description":
      "Alcatel 1T 7 inch Wi-Fi tablet comes with an incredibly compact form factor and lightweight body, weighing in at 245g and measuring 9.15mm thin, making it the ideal device for sharing in the home. Kids Mode will bring joy and safety to kids and parents alike. Kids will love the tablet's preloaded ad-free apps pre-approved for children's use. Parents will appreciate its built-in easy-to-use parental control panel that lets them set usage time and select which apps are available to use for kids.",
    "brand": "Alcatel",
    "category": "eletronics",
    "price": 129.0,
    "countInStock": 100,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "6",
    "title": "EKO 55 4K Ultra HD Android TV with Google Assistant - K550USG",
    "image": "/assets/tv.jpg",
    "description":
      "Experience outstanding entertainment with the New EKO TVs powered by Android TV. Blockbuster movies and TV shows. Streaming apps and multiplayer games. Android TV delivers a world of content, apps and games to your living room. With a range of content you'll be free to explore on Google Play Store. With a Bluetooth Remote allowing you to operate it from anywhere in the room.",
    "brand": "EKO",
    "category": "eletronics",
    "price": 499.0,
    "countInStock": 100,
    "rating": 4.5,
    "numReviews": 12,
  },
];