# Generated by Django 4.1.1 on 2022-10-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_order_taxprice_shippingaddress_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
