# Generated by Django 4.1.1 on 2022-10-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_shippingaddress_shippingprice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="email",
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
