# Generated by Django 4.1.1 on 2022-10-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_review_createdat"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
